// const number=1234.56
// console.log(number.toPrecision(4))
// const n1=120000000
// console.log(n1.toFixed(5))
// console.log(n1.toLocaleString())
// console.log(Math)
// console.log(Math.floor(3.7))
// console.log(Math.pow(2,3))
// console.log(Math.max(2,3,4,5))
// console.log(Math.min(2,3,4,5))
// console.log(Math.round(5.8))
// console.log(Math.ceil(3.7))
let d=new Date()
console.log(d.toDateString())
console.log(d.toLocaleString())
let date=new Date("12-26-2006")
console.log(date.toLocaleString())
let dt=new Date()
console.log(dt)
console.log(dt.getMonth()+1)
console.log(dt.getDay())
